name: Build and Deploy Adaptive Learning Platform

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, lti-service, frontend-service]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push User Service
      if: matrix.service == 'user-service'
      uses: docker/build-push-action@v5
      with:
        context: ./userservice
        file: ./userservice/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/adaptive-learning-user-service:latest
          ${{ env.DOCKER_REGISTRY }}/adaptive-learning-user-service:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push LTI Service
      if: matrix.service == 'lti-service'
      uses: docker/build-push-action@v5
      with:
        context: ./lti-service-python
        file: ./lti-service-python/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/adaptive-learning-lti-service:latest
          ${{ env.DOCKER_REGISTRY }}/adaptive-learning-lti-service:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Frontend Service
      if: matrix.service == 'frontend-service'
      uses: docker/build-push-action@v5
      with:
        context: ./FE-service-v2
        file: ./FE-service-v2/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/adaptive-learning-frontend:latest
          ${{ env.DOCKER_REGISTRY }}/adaptive-learning-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /opt/adaptive-learning
          
          # Pull latest code
          git pull origin main
          
          # Pull latest Docker images
          docker-compose -f docker-compose.prod.yml pull
          
          # Stop existing services
          docker-compose -f docker-compose.prod.yml down
          
          # Start services with new images
          docker-compose -f docker-compose.prod.yml up -d
          
          # Clean up old images
          docker image prune -f
          
          # Show status
          docker-compose -f docker-compose.prod.yml ps
          
          # Show logs for troubleshooting
          docker-compose -f docker-compose.prod.yml logs --tail=50

    - name: Health Check
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          # Wait for services to start
          sleep 30
          
          # Health check
          echo "=== Health Check ==="
          curl -f http://localhost:8000 || echo "Kong Gateway not ready"
          curl -f http://localhost:8080/auth/health || echo "User Service not ready"
          curl -f http://localhost:8082/health || echo "LTI Service not ready"
          curl -f http://localhost:5173 || echo "Frontend Service not ready"