# Template cấu hình Eureka Client cho các microservice
# Copy nội dung này vào application.yml của từng service

spring:
  application:
    name: service-name # Thay đổi tên service tương ứng

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Tên service cho từng microservice:
# - lti-service (port 8082)
# - recommendation-service (port 8083) 
# - course-service (port 8084)
# - analytics-service (port 8085)
# - user-service (port 8086)
# - common-service (port tùy chọn)
