#!/usr/bin/env python3
"""
Test LLM Cluster Profiling API
"""

import requests
import json

API_BASE = "http://localhost:8080/api"


def print_section(title):
    """Print section header"""
    print("\n" + "=" * 80)
    print(f"  {title}")
    print("=" * 80)


def test_list_clusters():
    """Test GET /api/clusters/list"""
    print_section("1. LIST ALL CLUSTERS")
    
    response = requests.get(f"{API_BASE}/clusters/list")
    
    if response.status_code == 200:
        data = response.json()
        
        print(f"\n✅ Total clusters: {data['total_clusters']}")
        print(f"✅ Total students: {data['total_students']}")
        
        print(f"\n📊 Clusters:")
        for cluster in data['clusters']:
            print(f"  {cluster['cluster_id']}: {cluster['profile_name']}")
            print(f"     Students: {cluster['n_students']} ({cluster['percentage']:.1f}%)")
        
        return True
    else:
        print(f"❌ Failed: {response.status_code}")
        print(response.text)
        return False


def test_get_cluster_info(cluster_id=0):
    """Test GET /api/clusters/{cluster_id}"""
    print_section(f"2. GET CLUSTER {cluster_id} INFO")
    
    response = requests.get(f"{API_BASE}/clusters/{cluster_id}")
    
    if response.status_code == 200:
        data = response.json()
        
        print(f"\n📊 Cluster {data['cluster_id']}:")
        print(f"  Students: {data['statistics']['n_students']} ({data['statistics']['percentage']:.1f}%)")
        
        print(f"\n  Top 3 Features:")
        for feat in data['statistics']['top_features'][:3]:
            print(f"    • {feat['feature']}: {feat['interpretation']} (z={feat['z_score']:.2f})")
        
        if data.get('existing_profile'):
            profile = data['existing_profile']
            print(f"\n  Existing Profile:")
            print(f"    Name: {profile.get('profile_name', 'N/A')}")
            print(f"    Desc: {profile.get('description', 'N/A')[:100]}...")
        else:
            print(f"\n  ⚠️  No existing LLM profile")
        
        return True
    else:
        print(f"❌ Failed: {response.status_code}")
        print(response.text)
        return False


def test_generate_profile(cluster_id=0):
    """Test POST /api/clusters/{cluster_id}/profile"""
    print_section(f"3. GENERATE LLM PROFILE FOR CLUSTER {cluster_id}")
    
    print(f"\n⏳ Generating LLM profile (this may take 5-10 seconds)...")
    
    response = requests.post(f"{API_BASE}/clusters/{cluster_id}/profile")
    
    if response.status_code == 200:
        data = response.json()
        profile = data['profile']
        
        print(f"\n✅ Generated by: {data['llm_provider'].upper()}")
        print(f"\n📝 Profile Name: {profile.get('profile_name', 'N/A')}")
        print(f"\n📖 Description:")
        print(f"  {profile.get('description', 'N/A')}")
        
        print(f"\n💪 Strengths:")
        for strength in profile.get('strengths', []):
            print(f"  • {strength}")
        
        print(f"\n⚠️  Weaknesses:")
        for weakness in profile.get('weaknesses', []):
            print(f"  • {weakness}")
        
        print(f"\n💡 Recommendations:")
        for i, rec in enumerate(profile.get('recommendations', []), 1):
            print(f"  {i}. {rec}")
        
        if 'key_characteristics' in profile:
            print(f"\n🎯 Key Characteristics:")
            for char in profile['key_characteristics']:
                print(f"  • {char}")
        
        return True
        
    elif response.status_code == 503:
        print(f"\n⚠️  LLM not available")
        print(f"   {response.json().get('detail', 'Unknown error')}")
        print(f"\n💡 To enable LLM profiling:")
        print(f"   export GOOGLE_API_KEY='your-gemini-api-key'")
        print(f"   # or")
        print(f"   export OPENAI_API_KEY='your-openai-api-key'")
        return False
    else:
        print(f"❌ Failed: {response.status_code}")
        print(response.text)
        return False


def test_generate_all_profiles():
    """Test POST /api/clusters/profile-all"""
    print_section("4. GENERATE ALL CLUSTER PROFILES")
    
    print(f"\n⏳ Generating profiles for all clusters (this may take 30-60 seconds)...")
    print(f"   Please wait...")
    
    response = requests.post(f"{API_BASE}/clusters/profile-all")
    
    if response.status_code == 200:
        data = response.json()
        
        print(f"\n✅ Generated profiles for {data['total_clusters']} clusters")
        print(f"✅ LLM Provider: {data['llm_provider'].upper()}")
        
        print(f"\n📋 Cluster Profiles:")
        for cluster in data['clusters']:
            profile = cluster['profile']
            print(f"\n  Cluster {cluster['cluster_id']}: {profile.get('profile_name', 'N/A')}")
            print(f"    Students: {cluster['n_students']} ({cluster['percentage']:.1f}%)")
            print(f"    Desc: {profile.get('description', 'N/A')[:80]}...")
        
        return True
        
    elif response.status_code == 503:
        print(f"\n⚠️  LLM not available")
        print(f"   {response.json().get('detail', 'Unknown error')}")
        return False
    else:
        print(f"❌ Failed: {response.status_code}")
        print(response.text)
        return False


def test_export_report():
    """Test GET /api/clusters/export/report"""
    print_section("5. EXPORT FULL REPORT")
    
    print(f"\n⏳ Generating and exporting full report...")
    
    response = requests.get(f"{API_BASE}/clusters/export/report")
    
    if response.status_code == 200:
        data = response.json()
        
        print(f"\n✅ {data['message']}")
        print(f"\n📁 Output Directory: {data['output_dir']}")
        print(f"  • JSON: {data['json_file']}")
        print(f"  • TXT:  {data['txt_file']}")
        
        return True
        
    elif response.status_code == 503:
        print(f"\n⚠️  LLM not available")
        print(f"   {response.json().get('detail', 'Unknown error')}")
        return False
    else:
        print(f"❌ Failed: {response.status_code}")
        print(response.text)
        return False


def main():
    """Run all tests"""
    print("\n" + "=" * 80)
    print("  🧪 LLM CLUSTER PROFILING API TESTS")
    print("=" * 80)
    print("\n📡 API Base URL:", API_BASE)
    
    try:
        # Test endpoints
        test_list_clusters()
        test_get_cluster_info(cluster_id=0)
        test_generate_profile(cluster_id=0)
        
        # Optional: test all profiles (takes longer)
        print("\n" + "=" * 80)
        print("  Optional: Generate All Profiles")
        print("=" * 80)
        user_input = input("\n⚠️  Generate profiles for ALL clusters? This may take 30-60 seconds. (yes/no): ")
        if user_input.lower() == 'yes':
            test_generate_all_profiles()
            test_export_report()
        
        print("\n" + "=" * 80)
        print("  ✅ TESTS COMPLETED")
        print("=" * 80)
        
        print("\n💡 Available Endpoints:")
        print("   GET  /api/clusters/list                    - List all clusters")
        print("   GET  /api/clusters/{id}                    - Get cluster info")
        print("   POST /api/clusters/{id}/profile            - Generate LLM profile for one cluster")
        print("   POST /api/clusters/profile-all             - Generate profiles for all clusters")
        print("   GET  /api/clusters/export/report           - Export full report")
        
    except requests.exceptions.ConnectionError:
        print("\n" + "=" * 80)
        print("  ❌ CONNECTION ERROR")
        print("=" * 80)
        print("\nCannot connect to API. Please start the server first:")
        print("  uvicorn api_service:app --reload --port 8080")


if __name__ == '__main__':
    main()
